name: Administer App validation
on:
    push:
        branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Validate new app
        run: bun run index.ts --git-enabled --${{ secrets.ADMINISTER_TOKEN }}

      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          else
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add .
            git commit -m "Cleanup after app validation"

            git push
          fi
